### ISSUE TITLE
Timer very unprecise and unpredictable

### ISSUE THREAD

**Issue by HaknCo** [anakod/Sming#56]
Hi,
I tested the Basic_Blink example and compared the output against the Blink example from the Arduino IDE port (version from 7.May). Both examples toggle PIN2 every 500 ms. You can see output below.

The Arduino Blink looks like this. Signal looks as expected.
![arduino blink](https://cloud.githubusercontent.com/assets/12210358/7554350/40e5205c-f725-11e4-84ce-7be51d00f724.png)

Now look at the Sming output. Totally weird.
![sming blink](https://cloud.githubusercontent.com/assets/12210358/7554352/4e47db90-f725-11e4-82fb-244c5f5d7c6d.png)

 I also tried the pull request from hreintke, who updated Timer to use delegates. 
Same result.

Any suggestions ?

Regards

**Comment by anakod** [comment]
I'm sure this isn't timer issue, something else affects on this pin in same time. You work this original example, yes? At first, please try to change selected pin number.

**Comment by tonycorona** [comment]
Maybe I'm having the same issue when compiling the Sming blink example, the led blinks but very unregular, normal blink example works okay. I think it is because the ESP is constantly rebooting. I can compile and flash al the normal examples using eclipse and they work okay, i can also compile and flash all the Sming examples without error but they don't work? Only the blink example works sort of... ;) I also noticed the blue led on the ESP constantly blinking?

**Comment by tonycorona** [comment]
Upgraded SDK to v1.0.1b1 and now it's working okay :+1:

**Comment by anakod** [comment]
Yes, it can be related to the https://github.com/kadamski/esp-lwip/issues/7
Unfortunately, author doesn't solve last SDK compatiblity issues yet.

**Comment by anakod** [comment]
Can be closed?

**Comment by HaknCo** [comment]
Just checked out last version. Problem disappeared. Blink example works as expected.
Thanks.
